Sort Contributors, Add links to Orcid, Github, Google Scholar
elixir-cloud-aai/elixir-cloud-aai.github.io pull request #14
Opened 2022-10-26 09:24 UTC by git-anurag-hub

This PR solves the following issues: 
- #12
- #13 

@uniqueg

2022-10-28 15:15 UTC, uniqueg requested changes
Great! I'll try to rebuild - let's hope it works.

As for the PR: Looks like [ResearchGate](https://www.researchgate.net/) is missing?
Could you still add that?

2022-10-28 16:55 UTC, uniqueg commented
I have added ResearchGate. But had to restore the `components/News.js` page to the previous state because otherwise the page wouldn't build. Now the news is not functional still/again, but at least the page builds.

I also hid the mouse overs on the Ion Icons (as it introduced incosistency with the PNG icons pulled from the CDN) and replaced the "school" icon with the real Google Scholar icon (also from the icons8 CDN).

Page is up with these changes: https://elixir-cloud.dcc.sib.swiss/contributors
Seems fine to me.

However, we need to credit the icons8 (see [license](https://icons8.com/license)) on the contributors page. Can you please take care of that (just add it to the bottom of the page, below the contributor cards) and then merge?

2022-10-28 16:57 UTC, git-anurag-hub commented
Yeah Sure Alex! Will do that!

2022-10-29 14:11 UTC, uniqueg approved these changes

2022-10-29 14:11 UTC, merged